parameters:
#    son_user.example.class: SON\UserBundle\Example

services:
#    son_user.example:
#        class: %son_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
